[Config]
Dependencies=rootfs

[Output]
Format=disk
Output=pocketlab-device
ImageId=pocketlab-device
ManifestFormat=json
CompressOutput=no
SplitArtifacts=

[Content]
BaseTrees=%O/rootfs
Bootable=no
Bootloader=none
UnifiedKernelImages=none
KernelModulesInitrd=no
MakeInitrd=no
Ssh=never
WithRecommends=no
CleanPackageMetadata=no

Packages=
    kernel
    kernel-modules
    kernel-modules-extra
    dracut
