[Distribution]
Distribution=fedora
Release=rawhide
Architecture=arm64

[Output]
Format=disk
Output=pocketlab
OutputDirectory=mkosi.output
CompressOutput=no
ImageId=pocketlab
ManifestFormat=json
SplitArtifacts=

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
MakeInitrd=no
Ssh=never
WithRecommends=yes
CleanPackageMetadata=no
RemoveFiles=
    /etc/fstab

# Development image: keep UART login possible while Phosh/display bring-up is in flux.
RootPassword=147147

Packages=
    @^phosh-desktop-environment

    initial-setup-gui-wayland-generic

    kernel
    kernel-modules
    kernel-modules-extra
    dracut
    e2fsprogs
    kmod

    ModemManager
    NetworkManager
    NetworkManager-wifi
    NetworkManager-wwan
    openssh-server
    qcom-firmware
    blob-wrangler
    qrtr
    rmtfs
    tqftpserv

    dnf5-plugins
    glibc-all-langpacks
    plymouth
    plymouth-theme-spinner
    sudo
    systemd-resolved
    vim-minimal
    zram-generator-defaults

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
