[Distribution]
Distribution=fedora
Release=rawhide
Architecture=arm64

[Output]
Format=disk
Output=pocketlab
OutputDirectory=mkosi.output
CompressOutput=no
ImageId=pocketlab
ManifestFormat=json
SplitArtifacts=

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
MakeInitrd=no
Ssh=never
WithRecommends=no
CleanPackageMetadata=no
RemoveFiles=
    /etc/fstab

# Development image: keep UART login possible while Phosh/display bring-up is in flux.
RootPassword=147147

Packages=
    initial-setup-gui-wayland-generic

    kernel
    kernel-modules
    kernel-modules-extra
    dracut
    e2fsprogs
    kmod

    cryptsetup
    default-editor
    dnf5
    dnf5-plugins
    glibc-all-langpacks
    openssh-server
    plymouth
    plymouth-theme-spinner
    sudo
    systemd
    systemd-udev
    systemd-resolved
    vim-minimal
    zram-generator-defaults

    phoc
    phosh
    phosh-mobile-settings
    phrog
    feedbackd
    mesa-dri-drivers
    stevia

    calls
    chatty
    epiphany
    gnome-calculator
    gnome-calendar
    gnome-clocks
    gnome-console
    gnome-contacts
    gnome-maps
    gnome-photos
    gnome-software
    phosh-tour
    pavucontrol
    pinentry-gnome3
    showtime

    alsa-ucm
    alsa-utils
    gstreamer1-plugin-dav1d
    gstreamer1-plugin-libav
    gstreamer1-plugin-openh264
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-good
    gstreamer1-plugins-ugly-free
    PackageKit-gstreamer-plugin
    pipewire-alsa
    pipewire-config-raop
    pipewire-gstreamer
    pipewire-pulseaudio
    pipewire-utils
    wireplumber

    ModemManager
    NetworkManager
    NetworkManager-config-connectivity-fedora
    NetworkManager-wifi
    NetworkManager-wwan
    wpa_supplicant

    atheros-firmware
    qcom-firmware
    blob-wrangler
    qrtr
    rmtfs
    tqftpserv

[Build]
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
